burger/burger/app/urls.py
#from django.contrib import admin
from django.urls import path
from . import views
from app.views import SignUp, user_login, ThanksPage
app_name = 'app'

urlpatterns = [
  path('signup/',views.SignUp,name='signup'),
  path('login/',views.user_login,name='login'),
  path('thanks/', ThanksPage.as_view(),name='thanks'),
  
 
]

burger/burger/burger/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from app.views import Index, About, Order, Menu, ThanksPage,OrderConfirmation, SignUp, user_login
from django.contrib.auth import views as auth_views 
#from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls',namespace='app')),
    path('', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('menu/', Menu.as_view(), name='menu'),
    path('order/', Order.as_view(), name='order'),
    path('order_confirmation',OrderConfirmation.as_view(),name='order_confirmation'),
    path('thanks/', ThanksPage.as_view(),name='thanks'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

burger/burger/app/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to ='profile_pics',blank=True)
  
    def __str__(self):
        
        return self.user.username
        
        
class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ManyToManyField('Category', related_name='item')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class OrderModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    items = models.ManyToManyField(
        'MenuItem', related_name='order', blank=True)

    def __str__(self):
        return f'Order: {self.created_on.strftime("%b %d %I: %M %p")}'
        
 

burger/burger/app/forms.py
from django import forms 
from django.contrib.auth.models import User
from app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
  
    class Meta:
        model = User 
        fields = ('username','email','password')

    
class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


      
    

burger/burger/app/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy
from django.views.generic import CreateView,TemplateView
from django.views import View
from django.http import HttpResponseRedirect, HttpResponse
from app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.decorators import login_required
from .models import MenuItem, Category, OrderModel


class ThanksPage(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'app/thanks.html')
      
class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'app/index.html')

class Menu(View):
  def get(self, request, *args, **kwargs):
    return render(request,'app/menu.html')
    
class About(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'app/about.html')

class Order(View):
    def get(self, request, *args, **kwargs):
      success_url = reverse_lazy("order_confirmation")
      return render(request, 'app/order.html')#context)

class OrderConfirmation(View):
    def get(self, request, *args, **kwargs):
        """
        # get every item from each category
        patty = MenuItem.objects.filter(
            category__name__contains='Patty')
        cheese = MenuItem.objects.filter(category__name__contains='Cheese')
        tomatoes = MenuItem.objects.filter(category__name__contains='Tomatoes')
        drinks = MenuItem.objects.filter(category__name__contains='Dirnk')

        # pass into context
        context = {
            'patty': patty,
            'cheese': cheese,
            'tomatoes': tomatoes,
            'drinks': drinks,
        }
        # render the template
        return render(request, 'app/order.html', context)

    def post(self, request, *args, **kwargs):
        order_items = {
            'items': []
        }

        items = request.POST.getlist('items[]')

        for item in items:
            menu_item = MenuItem.objects.get(pk__contains=int(item))
            item_data = {
                'id': menu_item.pk,
                'name': menu_item.name,
                'price': menu_item.price
            }

            order_items['items'].append(item_data)

            price = 0
            item_ids = []

        for item in order_items['items']:
            price += item['price']
            item_ids.append(item['id'])

        order = OrderModel.objects.create(price=price)
        order.items.add(*item_ids)

        context = {
            'items': order_items['items'],
            'price': price
        }
      """
        return render(request, 'app/order_confirmation.html')
        
@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse_lazy('index'))

def SignUp(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'app/signup.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse_lazy('thanks'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'app/login.html', {})
       
        
        

 

burger/burger/app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
            <h1>About Development!</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-1">
        <div class="col-md-10 col-sm-12 offset-md-1 p-4 text-center">
            <p>This is started on 09/09/2022</p>
            <p>updating : 10/09/2022 time:12:38-4:49 p.m</p>
            <p>updating : 10/09/2022 time: 9:46-10:00 p.m</p>
            <p>updating : 10/09/2022 time: 11:09p.m - 11:45 p.m </p>
            <p>updating : 11/09/2022 time: 9:00 a.m - 9:46 a.m </p>
            <p>updating : 11/09/2022 time: 9:45 -10:04 a.m</p>
            <p>udating : 11/09/2022 time: 9:30 p.m - 12:03 p.m</p>
            <p>updating : 12/09/2022 time: 6:45 a.m - 7:49 - 8:18 a.m</p>
            <p>updating 12:11 p.m - 12:15 p.m </p>
            <p>updating 6:27 p.m - 11:05 p.m </p>
            <p>updating 13/09/2022 8:07 a.m - 9:02 a.m</p>
            <p>updating 7:32 p.m - 10:07 p.m </p>
            <p>Updating 14/09/2023 6:54 a.m - 8:11 a.m</p>
            <p>Updating 14/09/2022 10:02 a.m - 11:28 a.m</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock content %}

burger/burger/app/templates/app/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", inital-scale=1.0, shrink-to-fit=no">
    <title>BURGERR</title>
   
    

    <!-- Font -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
</head>
<body>
    {% include 'app/navigation.html' %}
    {% block content %}
    {% static 'images/burger.png' %}
    {% endblock content %}
    {% include 'app/footer.html' %}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>
</html>

burger/burger/app/templates/app/footer.html
{% load static %}
<footer class="page-footer font-small indigo fixed-bottom">
    <div class="footer-copyright text-center py-3">&copy GIRIJA   
        <a class="ml-2" href="{% url 'app:login' %}">Login</a>
        <a class="ml-3" href="{% url 'app:signup' %}">Sign Up</a> 
    </div>
</footer>
<!-- href="{% url 'admin:index' %}"

burger/burger/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
            <h1>Choose what goes into your BURGER</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-1">
        <div class="card col-md-5 col-sm-12 offset-md-1 p-4 text-center">
            <h2>Place an Order!</h2>
            <a href="{% url 'order' %}" class="btn btn-outline-primary">Order Now!</a>
        </div>
    </div>
</div>
{% endblock content %}

burger/burger/app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}
{% load bootstrap3 %}
<div class="jumbotron">
  <div class="container">
  <h1>please login</h1>
  <form action="{% url 'app:login' %}" method="post">
    {% csrf_token %}
    <label for="username">username:</label>
    <input type="text" name="username" placeholder="user_name">
    <p></p>
    <label for="password">password:</label>
    <input type="password" name="password">
    <p></p>
    <input type="submit" name="" value="login">
  </form>
  </div>
</div>

{% endblock content %}

burger/burger/app/templates/app/menu.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
            <h1>Menu</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-1">
        <div class="col-md-10 col-sm-12 offset-md-1 p-4 text-center">
            <p>Onions    =  20/-</p>
            <p>Patty     =  40/-</p>
            <p>Lettuce   =  20/-</p>
            <p>Tomato    =  20/-</p>
            <p>Cheese    =  10/-</p>
        </div>
    </div>
</div>
{% endblock content %}

burger/burger/app/templates/app/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark indigo">
  <a class="navbar-brand" href="{% url 'index' %}">BURGER</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About Development</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'menu' %}">Menu</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'order' %}">Place an Order!</a>
      </li>
    </ul>
  </div>
</nav>

burger/burger/app/templates/app/order.html
{% extends 'app/base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="container mb-5">
   <div class="container">
    <div class="row justify-content-center mt-1">
        <div class="col-md-12 col-sm-12 p-4">
            <form method="GET">
                {% csrf_token %}
                <div class="pt-5">
                    <div class="row">
                        <div class="col-md-2 col-sm-12">
                            <img class="rounded" src="{% static "images/patty.png" %}" type="required" width="150" height="100"/>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="d-flex flex-row">
                                <div class="form-group form-check">
                                    <input type="checkbox" id="patty" class="checkbox" value="patty">
                                    <label class="form-check-label">patty</label>
                                </div>
                                <p class="font-weight-bold pl-5">20/-</p>
                            </div>
                            <p>delicious</p>
                        </div>
                    </div>
                    <hr />
                </div>

                <div class="pt-5">
                    <div class="row mt-4">
                        <div class="col-md-2 col-sm-12">
                            <img class="rounded" src="{% static "images/tomato.png" %}" width="150" height="100"/>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="d-flex flex-row">
                                <div class="form-group form-check">
                                    <input type="checkbox" id="tomato" class="checkbox" value="tomato">
                                    <label class="form-check-label">Tomato</label>
                                </div>
                                <p class="font-weight-bold pl-5">20/-</p></p>
                            </div>
                            <p>Redish</p>
                        </div>
                    </div>
                    <hr />
                </div>

                <div class="pt-5">
                    <div class="row mt-4">
                        <div class="col-md-2 col-sm-12">
                            <img class="rounded" src="{% static 'images/cheese.png' %}" width="150" height="100"/>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="d-flex flex-row">
                                <div class="form-group form-check">
                                    <input type="checkbox" id="cheese" class="checkbox" value="cheese">
                                    <label class="form-check-label">Cheese</label>
                                </div>
                                <p class="font-weight-bold pl-5">10/-</p>
                            </div>
                            <p>cheesey</p>
                        </div>
                    </div>
                    <hr />
                </div>
                <div class="pt-5">
                    <div class="row mt-4">
                        <div class="col-md-2 col-sm-12">
                            <img class="rounded" src="{% static "images/onion.png" %}" width="150" height="100"/>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="d-flex flex-row">
                                <div class="form-group form-check">
                                    <input type="checkbox" id="onion" class="checkbox" value="onion">
                                    <label class="form-check-label">Onion</label>
                                </div>
                                <p class="font-weight-bold pl-5">20/-</p>
                            </div>
                            <p>tasty</p>
                        </div>
                    </div>
                    <hr />
                </div>
                <div class="pt-5">
                    <div class="row mt-4">
                        <div class="col-md-2 col-sm-12">
                            <img class="rounded" src="{% static "images/lettuce.png" %}" width="150" height="100"/>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="d-flex flex-row">
                                <div class="form-group form-check">
                                    <input type="checkbox" id="lettuce" class="checkbox" value="lettuce">
                                    <label class="form-check-label">Lettuce</label>
                                </div>
                                <p class="font-weight-bold pl-5">20/-</p>
                            </div>
                            <p>greeny</p>
                        </div>
                    </div>
                    <hr />
                </div>
            
                <a href="{% url 'order_confirmation' %}" class="btn btn-primary">Confirm!</a>
               
            </form>
        </div>
        
        <div class="print-value">
          <p id="valueList">You have orderded your burger with:</p>
          <link rel="stylesheet" href="{% static 'js/order.css' %}">
        </div>
    </div>
    </div>
</div>
{% endblock content %}
<!--<script src="order.js"></script>
<!--<script src="{% static "static/js/order.js" %}"></script> 

burger/burger/app/templates/app/order_confirmation.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>Order Submitted!</h1>
            <p>You should receive a confirmation email soon.</p>
            <a href="{% url 'index' %}">Go to the homepage</a>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12 text-center">
            <link rel="stylesheet" href="{% static 'js/order.css' %}">
            <h3 class="pb-3">Order Summary:</h3>
            <p class="font-weight-bold pt-4">Thanks you for ordering</p>
        </div>
    </div>
</div>
{% endblock content %}

<!--<script>
  document.getElementById('valueList').textContent=listArray
</script>
-->

burger/burger/app/templates/app/signup.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <a href="{% static "app/thanks.html" %}"></a><h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Signup">
        </form>

      {% endif %}
  </div>

    </div>

  

{% endblock content %}

burger/burger/app/templates/app/thanks.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>Thanks for login!</h1>
            <p>You should receive a confirmation email soon.</p>
            <a href="{% url 'order' %}">Go to the homepage</a>
        </div>
    </div>
{% endblock content %}